-- =========================================================================
-- COACHING CALL DISCUSSIONS: MONTHLY REFRESH
-- =========================================================================
-- Builds all intermediate temp tables, then loads the persistent
-- Carefirst_Sandbox tables for the current month. Historical months
-- are preserved (DELETE + INSERT keyed on REPORT_MONTH).
-- Re-running in the same month is idempotent.
--
-- Target tables (created by ddl_create_tables.sql):
--   Carefirst_Sandbox.COACHING_CALL_TOPICS
--   Carefirst_Sandbox.COACHING_CALL_TOBACCO
--   Carefirst_Sandbox.COACHING_CALL_GOALS
-- =========================================================================


-- =========================================================================
-- STEP 1A: CALLS - one per account per day, billable types only
-- =========================================================================
DROP TABLE IF EXISTS CALLS_ONE_PER_DAY;
CREATE LOCAL TEMP TABLE CALLS_ONE_PER_DAY ON COMMIT PRESERVE ROWS AS
SELECT ACCOUNT, GUID, CUSTOMERID, CALL_TYPE, CALL_DATE
FROM (
    SELECT
        MC.ACCOUNT,
        NVL(MC.DERIVED_GUID, MC.GUID)           AS GUID,
        MC.CUSTOMERID,
        TRIM(MC.DESCRIPTION)                     AS CALL_TYPE,
        TRUNC(MC.ENCOUNTERDATETIME)::DATE        AS CALL_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY MC.ACCOUNT, TRUNC(MC.ENCOUNTERDATETIME)::DATE
            ORDER BY MC.ENCOUNTERDATETIME DESC
        ) AS RN
    FROM BI_REPORTING.MEMBER_CALL_DATA MC
    JOIN (
        SELECT DISTINCT TRIM(CALL_DESCRIPTIONS) AS CALL_DESC
        FROM ENT_WH.CALLTYPE_XREF_VW
        WHERE PPPY_BILL_ELIG = 'Y' OR INTERACTION_ELIG = 'Y'
    ) CT ON UPPER(TRIM(MC.DESCRIPTION)) = UPPER(CT.CALL_DESC)
    WHERE UPPER(MC.CALL_STATUS) = 'SUCCESSFUL'
      AND UPPER(MC.DIRECTION) = 'OUTBOUND'
) X WHERE RN = 1;


-- =========================================================================
-- STEP 1B: LM TOPICS - one per account per day (frequency tiebreak)
-- =========================================================================
DROP TABLE IF EXISTS LM_TOPICS_DEDUPED;
CREATE LOCAL TEMP TABLE LM_TOPICS_DEDUPED ON COMMIT PRESERVE ROWS AS
SELECT ACCOUNT, TOPIC_DATE, RESPONSE_TEXT
FROM (
    SELECT T.ACCOUNT, TRUNC(T.RESPONSE_DATE)::DATE AS TOPIC_DATE, T.RESPONSE_TEXT,
        ROW_NUMBER() OVER (
            PARTITION BY T.ACCOUNT, TRUNC(T.RESPONSE_DATE)::DATE
            ORDER BY FREQ.CNT DESC, T.RESPONSE_TEXT ASC
        ) AS RN
    FROM ENT_WH.COACH_NOTES_WORKFLOW T
    JOIN (
        SELECT ACCOUNT, RESPONSE_TEXT, COUNT(*) AS CNT
        FROM ENT_WH.COACH_NOTES_WORKFLOW
        WHERE QUESTION_ID IN ('502533','502758')
        GROUP BY 1, 2
    ) FREQ ON T.ACCOUNT = FREQ.ACCOUNT AND T.RESPONSE_TEXT = FREQ.RESPONSE_TEXT
    WHERE T.QUESTION_ID IN ('502533','502758')
) X WHERE RN = 1;


-- =========================================================================
-- STEP 1C: DM TOPICS - one per account per day
-- =========================================================================
DROP TABLE IF EXISTS DM_TOPICS_DEDUPED;
CREATE LOCAL TEMP TABLE DM_TOPICS_DEDUPED ON COMMIT PRESERVE ROWS AS
SELECT ACCOUNT, TOPIC_DATE, RESPONSE_TEXT
FROM (
    SELECT T.ACCOUNT, TRUNC(T.RESPONSE_DATE)::DATE AS TOPIC_DATE, T.RESPONSE_TEXT,
        ROW_NUMBER() OVER (
            PARTITION BY T.ACCOUNT, TRUNC(T.RESPONSE_DATE)::DATE
            ORDER BY FREQ.CNT DESC, T.RESPONSE_TEXT ASC
        ) AS RN
    FROM ENT_WH.COACH_NOTES_WORKFLOW_DM T
    JOIN (
        SELECT ACCOUNT, RESPONSE_TEXT, COUNT(*) AS CNT
        FROM ENT_WH.COACH_NOTES_WORKFLOW_DM
        WHERE QUESTION_ID = '502599'
        GROUP BY 1, 2
    ) FREQ ON T.ACCOUNT = FREQ.ACCOUNT AND T.RESPONSE_TEXT = FREQ.RESPONSE_TEXT
    WHERE T.QUESTION_ID = '502599'
) X WHERE RN = 1;


-- =========================================================================
-- STEP 1D: Identify calls NOT resolved by Tier 1
-- =========================================================================
DROP TABLE IF EXISTS CALLS_NO_TIER1;
CREATE LOCAL TEMP TABLE CALLS_NO_TIER1 ON COMMIT PRESERVE ROWS AS
SELECT C.*
FROM CALLS_ONE_PER_DAY C
LEFT JOIN LM_TOPICS_DEDUPED LM ON C.ACCOUNT = LM.ACCOUNT AND C.CALL_DATE = LM.TOPIC_DATE
LEFT JOIN DM_TOPICS_DEDUPED DM ON C.ACCOUNT = DM.ACCOUNT AND C.CALL_DATE = DM.TOPIC_DATE
WHERE LM.ACCOUNT IS NULL AND DM.ACCOUNT IS NULL;


-- =========================================================================
-- STEP 1E: TIER 1.5 - Text inference (only for calls without Tier 1)
-- =========================================================================
DROP TABLE IF EXISTS GOAL_TEXT_TOPICS;
CREATE LOCAL TEMP TABLE GOAL_TEXT_TOPICS ON COMMIT PRESERVE ROWS AS
SELECT ACCOUNT, TOPIC_DATE, INFERRED_TOPIC
FROM (
    SELECT ACCOUNT, TOPIC_DATE, INFERRED_TOPIC,
        ROW_NUMBER() OVER (PARTITION BY ACCOUNT, TOPIC_DATE ORDER BY SRC_PRI ASC) AS RN
    FROM (
        SELECT
            T.ACCOUNT,
            TRUNC(T.RESPONSE_DATE)::DATE AS TOPIC_DATE,
            CASE
                WHEN UPPER(T.RESPONSE_TEXT) LIKE '%WEIGHT%' OR UPPER(T.RESPONSE_TEXT) LIKE '%LBS%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%POUND%' OR UPPER(T.RESPONSE_TEXT) LIKE '%BMI%'
                    THEN 'Weight Management'
                WHEN UPPER(T.RESPONSE_TEXT) LIKE '%EXERCIS%' OR UPPER(T.RESPONSE_TEXT) LIKE '%WALK%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%RUN %' OR UPPER(T.RESPONSE_TEXT) LIKE '%GYM%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%ACTIVE%' OR UPPER(T.RESPONSE_TEXT) LIKE '%STEPS%'
                    THEN 'Exercise'
                WHEN UPPER(T.RESPONSE_TEXT) LIKE '%STRESS%' OR UPPER(T.RESPONSE_TEXT) LIKE '%ANXI%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%DEPRESS%' OR UPPER(T.RESPONSE_TEXT) LIKE '%MENTAL%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%MINDFUL%'
                    THEN 'Stress Management'
                WHEN UPPER(T.RESPONSE_TEXT) LIKE '%SLEEP%'
                    THEN 'Sleep Management'
                WHEN UPPER(T.RESPONSE_TEXT) LIKE '%EAT%' OR UPPER(T.RESPONSE_TEXT) LIKE '%DIET%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%NUTRI%' OR UPPER(T.RESPONSE_TEXT) LIKE '%MEAL%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%FOOD%' OR UPPER(T.RESPONSE_TEXT) LIKE '%CALORI%'
                    THEN 'Nutrition'
                WHEN UPPER(T.RESPONSE_TEXT) LIKE '%CHOLEST%' OR UPPER(T.RESPONSE_TEXT) LIKE '%A1C%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%BLOOD PRESSURE%' OR UPPER(T.RESPONSE_TEXT) LIKE '%DIABET%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%ASTHMA%' OR UPPER(T.RESPONSE_TEXT) LIKE '%COPD%'
                    THEN 'Chronic Disease State'
                WHEN UPPER(T.RESPONSE_TEXT) LIKE '%TOBACCO%' OR UPPER(T.RESPONSE_TEXT) LIKE '%SMOK%'
                    OR UPPER(T.RESPONSE_TEXT) LIKE '%QUIT%' OR UPPER(T.RESPONSE_TEXT) LIKE '%NICOTINE%'
                    THEN 'Tobacco Cessation'
                ELSE NULL
            END AS INFERRED_TOPIC,
            CASE WHEN T.QUESTION_ID = '502534' THEN 1 ELSE 2 END AS SRC_PRI
        FROM ENT_WH.COACH_NOTES_WORKFLOW T
        JOIN CALLS_NO_TIER1 C ON T.ACCOUNT = C.ACCOUNT AND TRUNC(T.RESPONSE_DATE)::DATE = C.CALL_DATE
        WHERE T.QUESTION_ID IN ('502534','502833')
          AND T.RESPONSE_TEXT IS NOT NULL AND LENGTH(TRIM(T.RESPONSE_TEXT)) > 2
          AND UPPER(TRIM(T.RESPONSE_TEXT)) NOT IN ('N/A','-','NA','NONE','.','N/A.')
          AND UPPER(TRIM(C.CALL_TYPE)) NOT IN ('TOBACCO','DIETARY REFERRAL','SPECIALTY','CLINICAL')

        UNION ALL

        SELECT
            T.ACCOUNT,
            TRUNC(T.RESPONSE_DATE)::DATE AS TOPIC_DATE,
            'Chronic Disease State' AS INFERRED_TOPIC,
            3 AS SRC_PRI
        FROM ENT_WH.COACH_NOTES_WORKFLOW_DM T
        JOIN CALLS_NO_TIER1 C ON T.ACCOUNT = C.ACCOUNT AND TRUNC(T.RESPONSE_DATE)::DATE = C.CALL_DATE
        WHERE T.QUESTION_ID = '502616'
          AND T.RESPONSE_TEXT IS NOT NULL AND LENGTH(TRIM(T.RESPONSE_TEXT)) > 2
          AND UPPER(TRIM(T.RESPONSE_TEXT)) NOT IN ('N/A','-','NA','NONE','.','N/A.')
          AND UPPER(TRIM(C.CALL_TYPE)) NOT IN ('TOBACCO','DIETARY REFERRAL','SPECIALTY','CLINICAL')
    ) RAW
    WHERE INFERRED_TOPIC IS NOT NULL
) RANKED WHERE RN = 1;


-- =========================================================================
-- STEP 1F: TIER 3 - Most recent prior topic (180-day lookback)
-- =========================================================================
DROP TABLE IF EXISTS PRIOR_TOPICS;
CREATE LOCAL TEMP TABLE PRIOR_TOPICS ON COMMIT PRESERVE ROWS AS
SELECT ACCOUNT, CALL_DATE, PRIOR_RESPONSE_TEXT
FROM (
    SELECT C.ACCOUNT, C.CALL_DATE, T.RESPONSE_TEXT AS PRIOR_RESPONSE_TEXT,
        ROW_NUMBER() OVER (PARTITION BY C.ACCOUNT, C.CALL_DATE ORDER BY T.RESPONSE_DATE DESC) AS RN
    FROM CALLS_NO_TIER1 C
    JOIN ENT_WH.COACH_NOTES_WORKFLOW T
        ON C.ACCOUNT = T.ACCOUNT
        AND TRUNC(T.RESPONSE_DATE)::DATE < C.CALL_DATE
        AND TRUNC(T.RESPONSE_DATE)::DATE >= C.CALL_DATE - 180
    WHERE T.QUESTION_ID IN ('502533','502758')
      AND UPPER(TRIM(C.CALL_TYPE)) NOT IN ('TOBACCO','DIETARY REFERRAL','SPECIALTY','CLINICAL')
      AND NOT EXISTS (
          SELECT 1 FROM GOAL_TEXT_TOPICS GT
          WHERE GT.ACCOUNT = C.ACCOUNT AND GT.TOPIC_DATE = C.CALL_DATE
      )
) X WHERE RN = 1;


-- =========================================================================
-- STEP 1G: FINAL COACHING_TOPICS - assemble all tiers
-- =========================================================================
DROP TABLE IF EXISTS COACHING_TOPICS;
CREATE LOCAL TEMP TABLE COACHING_TOPICS ON COMMIT PRESERVE ROWS AS
SELECT
    C.ACCOUNT, C.GUID, C.CUSTOMERID, C.CALL_DATE, C.CALL_TYPE,
    COALESCE(LM.RESPONSE_TEXT, DM.RESPONSE_TEXT) AS RAW_TOPIC,
    CASE
        WHEN UPPER(LM.RESPONSE_TEXT) = 'EXERCISE'                  THEN 'Exercise'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'HEALTHY EATING'            THEN 'Nutrition'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'WEIGHT'                    THEN 'Weight Management'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'STRESS'                    THEN 'Stress Management'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'TOBACCO'                   THEN 'Tobacco Cessation'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'OTHER'                     THEN 'Other'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'OTHER - PHYSICAL/SOCIAL'   THEN 'Social Support'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'PHYSICAL ACTIVITY'             THEN 'Exercise'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'NUTRITION/WEIGHT MANAGEMENT'   THEN 'Nutrition'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'MENTAL WELL-BEING'             THEN 'Stress Management'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'RESTORATIVE SLEEP'             THEN 'Sleep Management'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'POSITIVE SOCIAL CONNECTIONS'   THEN 'Social Support'
        WHEN UPPER(LM.RESPONSE_TEXT) = 'AVOIDANCE OF RISKY SUBSTANCES' THEN 'Behavioral Health'
        WHEN DM.RESPONSE_TEXT IS NOT NULL       THEN 'Chronic Disease State'
        WHEN GT.INFERRED_TOPIC IS NOT NULL      THEN GT.INFERRED_TOPIC
        WHEN UPPER(TRIM(C.CALL_TYPE)) = 'TOBACCO'          THEN 'Tobacco Cessation'
        WHEN UPPER(TRIM(C.CALL_TYPE)) = 'DIETARY REFERRAL' THEN 'Nutrition'
        WHEN UPPER(TRIM(C.CALL_TYPE)) IN ('SPECIALTY','CLINICAL') THEN 'Chronic Disease State'
        WHEN PT.PRIOR_RESPONSE_TEXT IS NOT NULL THEN
            CASE
                WHEN UPPER(PT.PRIOR_RESPONSE_TEXT) IN ('EXERCISE','PHYSICAL ACTIVITY') THEN 'Exercise'
                WHEN UPPER(PT.PRIOR_RESPONSE_TEXT) IN ('HEALTHY EATING','NUTRITION/WEIGHT MANAGEMENT') THEN 'Nutrition'
                WHEN UPPER(PT.PRIOR_RESPONSE_TEXT) = 'WEIGHT' THEN 'Weight Management'
                WHEN UPPER(PT.PRIOR_RESPONSE_TEXT) IN ('STRESS','MENTAL WELL-BEING') THEN 'Stress Management'
                WHEN UPPER(PT.PRIOR_RESPONSE_TEXT) = 'RESTORATIVE SLEEP' THEN 'Sleep Management'
                WHEN UPPER(PT.PRIOR_RESPONSE_TEXT) = 'TOBACCO' THEN 'Tobacco Cessation'
                WHEN UPPER(PT.PRIOR_RESPONSE_TEXT) = 'AVOIDANCE OF RISKY SUBSTANCES' THEN 'Behavioral Health'
                WHEN UPPER(PT.PRIOR_RESPONSE_TEXT) IN ('POSITIVE SOCIAL CONNECTIONS','OTHER - PHYSICAL/SOCIAL') THEN 'Social Support'
                WHEN UPPER(PT.PRIOR_RESPONSE_TEXT) = 'OTHER' THEN 'Other'
                ELSE 'General'
            END
        ELSE 'General'
    END AS REPORT_TOPIC,
    CASE
        WHEN LM.RESPONSE_TEXT IS NOT NULL THEN 'Tier 1: Date Match (LM)'
        WHEN DM.RESPONSE_TEXT IS NOT NULL THEN 'Tier 1: Date Match (DM)'
        WHEN GT.INFERRED_TOPIC IS NOT NULL THEN 'Tier 1.5: Text Inference'
        WHEN UPPER(TRIM(C.CALL_TYPE)) IN ('TOBACCO','DIETARY REFERRAL','SPECIALTY','CLINICAL') THEN 'Tier 2: Call Type'
        WHEN PT.PRIOR_RESPONSE_TEXT IS NOT NULL THEN 'Tier 3: Prior Topic'
        ELSE 'Tier 4: None'
    END AS TOPIC_SOURCE,
    CASE WHEN LM.RESPONSE_TEXT IS NOT NULL THEN 'LM'
         WHEN DM.RESPONSE_TEXT IS NOT NULL THEN 'DM' ELSE NULL END AS PROGRAM_TYPE
FROM CALLS_ONE_PER_DAY C
LEFT JOIN LM_TOPICS_DEDUPED LM ON C.ACCOUNT = LM.ACCOUNT AND C.CALL_DATE = LM.TOPIC_DATE
LEFT JOIN DM_TOPICS_DEDUPED DM ON C.ACCOUNT = DM.ACCOUNT AND C.CALL_DATE = DM.TOPIC_DATE AND LM.ACCOUNT IS NULL
LEFT JOIN GOAL_TEXT_TOPICS GT ON C.ACCOUNT = GT.ACCOUNT AND C.CALL_DATE = GT.TOPIC_DATE AND LM.ACCOUNT IS NULL AND DM.ACCOUNT IS NULL
LEFT JOIN PRIOR_TOPICS PT ON C.ACCOUNT = PT.ACCOUNT AND C.CALL_DATE = PT.CALL_DATE AND LM.ACCOUNT IS NULL AND DM.ACCOUNT IS NULL AND GT.ACCOUNT IS NULL;


-- =========================================================================
-- STEP 2: TOBACCO FLAG
-- =========================================================================
DROP TABLE IF EXISTS COACHING_TOBACCO;
CREATE LOCAL TEMP TABLE COACHING_TOBACCO ON COMMIT PRESERVE ROWS AS
SELECT DISTINCT ACCOUNT, GUID, 'Yes' AS TOBACCO_DISCUSSED
FROM COACHING_TOPICS
WHERE UPPER(RAW_TOPIC) = 'TOBACCO'
   OR UPPER(CALL_TYPE) = 'TOBACCO';


-- =========================================================================
-- STEP 3: GOALS
-- =========================================================================
DROP TABLE IF EXISTS COACHING_GOALS;
CREATE LOCAL TEMP TABLE COACHING_GOALS ON COMMIT PRESERVE ROWS AS
SELECT
    MA.ACCOUNT,
    CASE WHEN MA.ActionType_ID = 2 THEN 'Coach-Created'
         WHEN MA.ActionType_ID = 3 THEN 'System-Recommended' END AS GOAL_TYPE,
    CASE
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('EXERCISE','[EXERCISE]','*EXERCISE','[[*EXERCISE]]','*CIS EXERCISE','*CIS EXERICSE','EXERICSE','EXERISE','EXERCSE') THEN 'Exercise'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('HEALTHY EATING','[HEALTHY EATING]','[*HEALTHY EATING]','NUTRTION','HEATLHY EATING','HEALTH EATING','[NUTRITION]','DIET') THEN 'Nutrition'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('WEIGHT','[WEIGHT]','WEIGHT LOSS') THEN 'Weight Management'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('TOBACCO','[TOBACCO]') THEN 'Tobacco Cessation'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('STRESS','[*STRESS]','STRESS/EMOTIONAL WELL-BEING','DEPRESSION','MENTAL HEALTH','MINDFULNESS','ALCOHOL') THEN 'Mental/Behavioral Health'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('STRESS MANAGEMENT','SLEEP','CPAP') THEN 'Stress Management'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('SCREENING','[PREVENTATIVE CARE]','[*PREVENTATIVE CARE]','[*CARE GAPS]','SCREENING SOC','VACCINE','[VACCINE]') THEN 'Gaps in Care'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('DIABETES','[DIABETES]','DIABETES/CAD','CAD/DIABETES','DIABETES SOC','ASTHMA/COPD','ASTHMA','COPD','COPD/HF','[RESPIRATORY (ASTHMA/COPD)]','[ASTHMA/COPD]','[ASTHMA]','[COPD]','CAD/HF','CAD','HF','[CARDIAC (CAD/HF)]','[CAD]','[HF]','AFIB','FIBRO','OA','IBS','IBD','LBP','ARSD') THEN 'Condition Management'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('CHOLESTEROL','CHOL','TRIG','BP','BLOOD PRESSURE') THEN 'Condition Management'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('UTILIZATION RISK','HOSPITAL','[HOSPITALIZATION]','CRITICAL RISK EVENT FOLLOW-UP','APPOINTMENT ADHERENCE','APPOINTMENT','MAKE AND KEEP APPOINTMENTS','MEDICATION ADHERENCE','MEDICATION','MED ADHERENCE','SELF MANAGEMENT','SELF CARE','WORK ITEM','TIME MANAGEMENT','SCHEDULE ADHERENCE') THEN 'Condition Management'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('FINANCES','FINANCIAL WELLNESS','SAVINGS') THEN 'Financial'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) = 'SOCIAL WELLNESS' THEN 'Social'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) = 'SPIRITUAL HEALTH' THEN 'Spiritual'
        WHEN UPPER(SPLIT_PART(MA.Action_Name,':',1)) IN ('WATER','WATER INTAKE','PAIN MANAGEMENT') THEN 'Condition Management'
        ELSE 'Other'
    END AS GOAL_DOMAIN,
    CASE
        WHEN MA.ActionStatus_ID = 1 THEN 'Not Started'
        WHEN MA.ActionStatus_ID = 2 THEN 'In Progress'
        WHEN MA.ActionStatus_ID IN (3, 5) THEN 'Completed'
        WHEN MA.ActionStatus_ID = 4 THEN 'Withdrawn'
    END AS GOAL_STATUS,
    CASE WHEN MA.Action_Name LIKE '%:%' THEN TRIM(SUBSTR(MA.Action_Name, POSITION(':' IN MA.Action_Name)+1)) ELSE MA.Action_Name END AS GOAL_DESCRIPTION,
    MA.Action_Name AS RAW_ACTION_NAME,
    MA.MemberAction_ID, MA.ActionType_ID, MA.ActionStatus_ID, MA.FocusArea_ID,
    MA.Action_Date AS GOAL_SET_DATE, MA.Close_Date AS GOAL_CLOSE_DATE
FROM SCP.AH_MEMBER_ACTION MA
WHERE MA.ActionType_ID IN (2,3) AND MA.ActionStatus_ID IN (1, 2, 3, 4, 5)
  AND MA.Action_Name NOT LIKE 'Survey:%' AND MA.Action_Name NOT LIKE 'RED:%' AND MA.Action_Name NOT LIKE 'RED/%';


-- =========================================================================
-- STEP 4: BRIDGE GOALS TO GUID (current enrollment)
-- =========================================================================
DROP TABLE IF EXISTS COACHING_GOALS_NUMBERED;
CREATE LOCAL TEMP TABLE COACHING_GOALS_NUMBERED ON COMMIT PRESERVE ROWS AS
SELECT G.*, CE.CURRENTGUID, CE.GUID,
    ROW_NUMBER() OVER (PARTITION BY G.ACCOUNT ORDER BY G.GOAL_SET_DATE ASC, G.RAW_ACTION_NAME ASC) AS GOAL_NUMBER
FROM COACHING_GOALS G
JOIN (
    SELECT ACCOUNT, CURRENTGUID, GUID,
        ROW_NUMBER() OVER (PARTITION BY ACCOUNT ORDER BY BIENDDATE DESC) AS RN
    FROM BI_REPORTING.COACHING_ENROLLMENT_MODEL
    WHERE BIENDDATE >= CURRENT_DATE
) CE ON G.ACCOUNT = CE.ACCOUNT AND CE.RN = 1;


-- =========================================================================
-- STEP 5: LOAD PERSISTENT TABLES (delete current month + insert)
-- Uses REPORT_MONTH = 'YYYYMM' to partition data by run month.
-- Re-running for the same month is idempotent (deletes then reinserts).
-- Historical months are preserved.
-- =========================================================================

-- 5A: COACHING_CALL_TOPICS
DELETE FROM Carefirst_Sandbox.COACHING_CALL_TOPICS
WHERE REPORT_MONTH = TO_CHAR(SYSDATE, 'YYYYMM');

INSERT INTO Carefirst_Sandbox.COACHING_CALL_TOPICS
    (REPORT_MONTH, ACCOUNT, GUID, CUSTOMERID, CALL_DATE, CALL_TYPE, RAW_TOPIC, REPORT_TOPIC, TOPIC_SOURCE, PROGRAM_TYPE, REFRESH_DATE)
SELECT
    TO_CHAR(SYSDATE, 'YYYYMM'), ACCOUNT, GUID, CUSTOMERID, CALL_DATE, CALL_TYPE, RAW_TOPIC, REPORT_TOPIC, TOPIC_SOURCE, PROGRAM_TYPE, SYSDATE
FROM COACHING_TOPICS;

-- 5B: COACHING_CALL_TOBACCO
DELETE FROM Carefirst_Sandbox.COACHING_CALL_TOBACCO
WHERE REPORT_MONTH = TO_CHAR(SYSDATE, 'YYYYMM');

INSERT INTO Carefirst_Sandbox.COACHING_CALL_TOBACCO
    (REPORT_MONTH, ACCOUNT, GUID, TOBACCO_DISCUSSED, REFRESH_DATE)
SELECT
    TO_CHAR(SYSDATE, 'YYYYMM'), ACCOUNT, GUID, TOBACCO_DISCUSSED, SYSDATE
FROM COACHING_TOBACCO;

-- 5C: COACHING_CALL_GOALS
DELETE FROM Carefirst_Sandbox.COACHING_CALL_GOALS
WHERE REPORT_MONTH = TO_CHAR(SYSDATE, 'YYYYMM');

INSERT INTO Carefirst_Sandbox.COACHING_CALL_GOALS
    (REPORT_MONTH, ACCOUNT, GOAL_TYPE, GOAL_DOMAIN, GOAL_STATUS, GOAL_DESCRIPTION, RAW_ACTION_NAME,
     MEMBERACTION_ID, ACTIONTYPE_ID, ACTIONSTATUS_ID, FOCUSAREA_ID,
     GOAL_SET_DATE, GOAL_CLOSE_DATE, CURRENTGUID, GUID, GOAL_NUMBER, REFRESH_DATE)
SELECT
    TO_CHAR(SYSDATE, 'YYYYMM'), ACCOUNT, GOAL_TYPE, GOAL_DOMAIN, GOAL_STATUS, GOAL_DESCRIPTION, RAW_ACTION_NAME,
    MEMBERACTION_ID, ACTIONTYPE_ID, ACTIONSTATUS_ID, FOCUSAREA_ID,
    GOAL_SET_DATE, GOAL_CLOSE_DATE, CURRENTGUID, GUID, GOAL_NUMBER, SYSDATE
FROM COACHING_GOALS_NUMBERED;

